/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author PROPIETARIO
 */
public class Caso2 extends javax.swing.JFrame {

    /**
     * Creates new form Caso1
     */
    public Caso2() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLAlturaCalculada = new javax.swing.JLabel();
        jLCoeficienteC = new javax.swing.JLabel();
        jLDiametroC = new javax.swing.JLabel();
        jLLongitudC = new javax.swing.JLabel();
        jLAlturaC = new javax.swing.JLabel();
        jLCoeficienteB = new javax.swing.JLabel();
        jLDiametroB = new javax.swing.JLabel();
        jLLongitudB = new javax.swing.JLabel();
        jLAlturaB = new javax.swing.JLabel();
        jLCoeficienteA = new javax.swing.JLabel();
        jLDiametroA = new javax.swing.JLabel();
        jLAlturaA = new javax.swing.JLabel();
        jLLongitudA = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("QA + QB = QC");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLAlturaCalculada.setText("Altura: ");
        jPanel6.add(jLAlturaCalculada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, -1));

        jLCoeficienteC.setText("Ceficiente C: ");
        jPanel6.add(jLCoeficienteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 110, -1));

        jLDiametroC.setText("Díametro: ");
        jPanel6.add(jLDiametroC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 110, -1));

        jLLongitudC.setText("Longitud: ");
        jPanel6.add(jLLongitudC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, -1));

        jLAlturaC.setText("Altura: ");
        jPanel6.add(jLAlturaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, -1));

        jLCoeficienteB.setText("Coeficiente C:");
        jPanel6.add(jLCoeficienteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 130, -1));

        jLDiametroB.setText("Díametro: ");
        jPanel6.add(jLDiametroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, -1));

        jLLongitudB.setText("Longitud: ");
        jPanel6.add(jLLongitudB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, -1));

        jLAlturaB.setText("Altura: ");
        jPanel6.add(jLAlturaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 110, -1));

        jLCoeficienteA.setText("Coeficiente C: ");
        jPanel6.add(jLCoeficienteA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 130, -1));

        jLDiametroA.setText("Díametro: ");
        jPanel6.add(jLDiametroA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, -1));

        jLAlturaA.setText("Altura: ");
        jPanel6.add(jLAlturaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, -1));

        jLLongitudA.setText("Longitud: ");
        jPanel6.add(jLLongitudA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 110, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redimencion caso 2.png"))); // NOI18N
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLAlturaA;
    public javax.swing.JLabel jLAlturaB;
    public javax.swing.JLabel jLAlturaC;
    public javax.swing.JLabel jLAlturaCalculada;
    public javax.swing.JLabel jLCoeficienteA;
    public javax.swing.JLabel jLCoeficienteB;
    public javax.swing.JLabel jLCoeficienteC;
    public javax.swing.JLabel jLDiametroA;
    public javax.swing.JLabel jLDiametroB;
    public javax.swing.JLabel jLDiametroC;
    public javax.swing.JLabel jLLongitudA;
    public javax.swing.JLabel jLLongitudB;
    public javax.swing.JLabel jLLongitudC;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
