/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import main.MainProblema3Tanques;
/**
 *
 * @author PROPIETARIO
 */
public class Interfaz3Tanques extends javax.swing.JFrame {

    /**
     * Creates new form InterfazProblema3Tanques
     */
    public Interfaz3Tanques() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAlturaA = new javax.swing.JTextField();
        txtLongitudA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiametroA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCoeficienteCA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAlturaB = new javax.swing.JTextField();
        txtLongitudB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDiametroB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCoeficienteCB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAlturaC = new javax.swing.JTextField();
        txtLongitudC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDiametroC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCoeficienteCC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        txtLongitudC1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDiametroC1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCoeficienteCC1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        salidaCotaCalculada = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tanque A");

        jLabel3.setText("Altura (m)");

        txtAlturaA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaAKeyTyped(evt);
            }
        });

        txtLongitudA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudAKeyTyped(evt);
            }
        });

        jLabel4.setText("Longitud (m)");

        txtDiametroA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiametroAKeyTyped(evt);
            }
        });

        jLabel5.setText("Díametro (m)");

        txtCoeficienteCA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoeficienteCAKeyTyped(evt);
            }
        });

        jLabel6.setText("Coeficiente C");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlturaA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLongitudA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiametroA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoeficienteCA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAlturaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLongitudA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiametroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCoeficienteCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Problema de los 3 Tanques");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tanque B");

        jLabel8.setText("Altura (m)");

        txtAlturaB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaBKeyTyped(evt);
            }
        });

        txtLongitudB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudBKeyTyped(evt);
            }
        });

        jLabel9.setText("Longitud (m)");

        txtDiametroB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiametroBKeyTyped(evt);
            }
        });

        jLabel10.setText("Díametro (m)");

        txtCoeficienteCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoeficienteCBKeyTyped(evt);
            }
        });

        jLabel11.setText("Coeficiente C");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlturaB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLongitudB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiametroB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoeficienteCB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAlturaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLongitudB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiametroB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCoeficienteCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tanque C");

        jLabel13.setText("Altura (m)");

        txtAlturaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaCKeyTyped(evt);
            }
        });

        txtLongitudC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudCKeyTyped(evt);
            }
        });

        jLabel14.setText("Longitud (m)");

        txtDiametroC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiametroCKeyTyped(evt);
            }
        });

        jLabel15.setText("Díametro (m)");

        txtCoeficienteCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoeficienteCCKeyTyped(evt);
            }
        });

        jLabel16.setText("Coeficiente C");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlturaC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLongitudC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiametroC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoeficienteCC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel12)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAlturaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtLongitudC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDiametroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCoeficienteCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Datos Generales");

        jLabel18.setText("Error Aceptado");

        txtError.setText("0.0001");
        txtError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtErrorKeyTyped(evt);
            }
        });

        jLabel19.setText("Longitud");

        jLabel20.setText("Díametro");

        jLabel21.setText("Coeficiente C");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLongitudC1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiametroC1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoeficienteCC1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtLongitudC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtDiametroC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCoeficienteCC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        content.setPreferredSize(new java.awt.Dimension(505, 320));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        salidaCotaCalculada.setEditable(false);

        jLabel22.setText("Cota Calculada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnCalcular)
                        .addGap(150, 150, 150)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(salidaCotaCalculada, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(353, 353, 353))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(jButton1))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(salidaCotaCalculada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int numeroDeBucles= 0;
 
        double respuestaCota = 0;
        double respuestaError = 0;
        
        double e = 0.1;
        double error = 0.0001;
        boolean bandera = false;
        
        double cotaSuperior=0;
        double cotaInferior=0;
        
        double errorActual=0;
        double errorSiguiente=0;
        
        double cota2C;
        double errorCota2C;
        
        error = Double.parseDouble(txtError.getText());

        if (!txtAlturaA.getText().isEmpty() &&
        !txtAlturaB.getText().isEmpty() &&
        !txtAlturaC.getText().isEmpty() &&
        !txtLongitudA.getText().isEmpty() &&
        !txtLongitudB.getText().isEmpty() &&
        !txtLongitudC.getText().isEmpty() &&
        !txtDiametroA.getText().isEmpty() &&
        !txtDiametroB.getText().isEmpty() &&
        !txtDiametroC.getText().isEmpty() &&
        !txtCoeficienteCA.getText().isEmpty() &&
        !txtCoeficienteCB.getText().isEmpty() &&
        !txtCoeficienteCC.getText().isEmpty()) {

            double AlturaA = Double.parseDouble(txtAlturaA.getText());
            double AlturaB = Double.parseDouble(txtAlturaB.getText());
            double AlturaC = Double.parseDouble(txtAlturaC.getText());

            double LongitudA = Double.parseDouble(txtLongitudA.getText());
            double LongitudB = Double.parseDouble(txtLongitudB.getText());
            double LongitudC = Double.parseDouble(txtLongitudC.getText());

            double DiametroA = Double.parseDouble(txtDiametroA.getText());
            double DiametroB = Double.parseDouble(txtDiametroB.getText());
            double DiametroC = Double.parseDouble(txtDiametroC.getText());

            double CoeficienteCA = Double.parseDouble(txtCoeficienteCA.getText());
            double CoeficienteCB = Double.parseDouble(txtCoeficienteCB.getText());
            double CoeficienteCC = Double.parseDouble(txtCoeficienteCC.getText());
            
            if (AlturaA > AlturaB && AlturaB > AlturaC) {
                double[] ArregloA = {AlturaA, LongitudA, DiametroA, CoeficienteCA};
                double[] ArregloB = {AlturaB, LongitudB, DiametroB, CoeficienteCB};
                double[] ArregloC = {AlturaC, LongitudC, DiametroC, CoeficienteCC};

                double cota1 = AlturaA-e;
                double cota5 = AlturaB+e;
                double cota3 = (cota1+cota5)/2;
                double cota2 = (cota1+cota3)/2; 
                double cota4 = (cota3+cota5)/2; 

                double[] arregloCota = {cota1, cota2, cota3, cota4, cota5};

                double error1 = MainProblema3Tanques.calcularError(ArregloA, ArregloB, ArregloC, cota1);
                double error2 = MainProblema3Tanques.calcularError(ArregloA, ArregloB, ArregloC, cota2);
                double error3 = MainProblema3Tanques.calcularError(ArregloA, ArregloB, ArregloC, cota3);
                double error4 = MainProblema3Tanques.calcularError(ArregloA, ArregloB, ArregloC, cota4);
                double error5 = MainProblema3Tanques.calcularError(ArregloA, ArregloB, ArregloC, cota5);

                double[] arregloDeError = {error1, error2, error3, error4, error5};

                boolean enMedio = false;
                boolean BerrorCota= false;
                boolean BerrorSiguiente= false;
                double[] arregloError2;
                double[] arregloCota2; 

                if (!((error1>0 && error2>0 && error3>0 && error4>0 && error5>0) || (error1<0 && error2<0 && error3<0 && error4<0 && error5<0))) {
                    for (int i = 0; i < arregloDeError.length - 1; i++) {
                        errorActual = arregloDeError[i];
                        errorSiguiente = arregloDeError[i + 1];
                        if (errorActual < 0 && errorSiguiente > 0) {
                            System.out.println("El valor 0 está entre los errores " + errorActual + " y " + errorSiguiente);
                            cotaSuperior = arregloCota[i+1];
                            cotaInferior = arregloCota[i];
                            System.out.println("cota equivalentes "+cotaInferior+ " y "+ +cotaSuperior);
                            enMedio = true;
                            break;  // Terminamos el bucle una vez que encontramos el 0
                        }
                    }
                    double cota = MainProblema3Tanques.interpolacion(errorActual, cotaInferior, errorSiguiente, cotaSuperior);
                    double errorCota = MainProblema3Tanques.calcularError(ArregloA, ArregloB, ArregloC, cota);
                    bandera = error>errorCota;
                    if (bandera == true) {
                        respuestaCota=cota;
                        respuestaError=errorCota;
                    }
                    while (bandera == false && numeroDeBucles < 100) {
                        if (errorCota > 0 && errorSiguiente > 0) {
                            cota2C = MainProblema3Tanques.interpolacion(errorCota, cota, errorActual, cotaInferior);
                        }
                        else{
                            cota2C = MainProblema3Tanques.interpolacion(errorCota, cota, errorSiguiente, cotaSuperior);
                        }
                        errorCota2C = MainProblema3Tanques.calcularError(ArregloA, ArregloB, ArregloC, cota2C);

                        if (errorCota > 0 && errorSiguiente > 0) {
                            errorSiguiente = errorCota;
                            cotaSuperior = cota; 
                        }
                        else{
                            errorActual = errorCota;
                            cotaInferior = cota; 
                        }
                        cota =cota2C;
                        errorCota = errorCota2C;
                        if (error>errorCota2C) {
                            bandera = true;
                            respuestaCota=cota;
                            respuestaError=error;
                        }
                        numeroDeBucles++;
                    } 
                    System.out.println("el número de iteraciones es:"+numeroDeBucles);
                    if (numeroDeBucles > 99) {
                        JOptionPane.showMessageDialog(this, "los datos ingresados son incogruentes, por favor verifique", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        salidaCotaCalculada.setText(String.valueOf(respuestaCota));

                        Caso1 interfazCaso1 = new Caso1();
                        interfazCaso1.setSize(505, 320);
                        interfazCaso1.setLocation(0, 0);
                        interfazCaso1.jLAlturaA.setText(interfazCaso1.jLAlturaA.getText()+txtAlturaA.getText());
                        interfazCaso1.jLAlturaB.setText(interfazCaso1.jLAlturaB.getText()+txtAlturaB.getText());
                        interfazCaso1.jLAlturaC.setText(interfazCaso1.jLAlturaC.getText()+txtAlturaC.getText());

                        interfazCaso1.jLLongitudA.setText(interfazCaso1.jLLongitudA.getText()+txtLongitudA.getText());
                        interfazCaso1.jLLongitudB.setText(interfazCaso1.jLLongitudB.getText()+txtLongitudB.getText());
                        interfazCaso1.jLLongitudC.setText(interfazCaso1.jLLongitudC.getText()+txtLongitudC.getText());

                        interfazCaso1.jLDiametroA.setText(interfazCaso1.jLDiametroA.getText()+txtDiametroA.getText());
                        interfazCaso1.jLDiametroB.setText(interfazCaso1.jLDiametroB.getText()+txtDiametroB.getText());
                        interfazCaso1.jLDiametroC.setText(interfazCaso1.jLDiametroC.getText()+txtDiametroC.getText());

                        interfazCaso1.jLCoeficienteA.setText(interfazCaso1.jLCoeficienteA.getText()+txtCoeficienteCA.getText());
                        interfazCaso1.jLCoeficienteB.setText(interfazCaso1.jLCoeficienteB.getText()+txtCoeficienteCB.getText());
                        interfazCaso1.jLCoeficienteC.setText(interfazCaso1.jLCoeficienteC.getText()+txtCoeficienteCC.getText());

                        interfazCaso1.jLAlturaCalculada.setText(interfazCaso1.jLAlturaCalculada.getText()+String.valueOf(respuestaCota));

                        content.removeAll();
                        content.add(interfazCaso1.jPanel6, BorderLayout.CENTER);
                        content.revalidate();
                        content.repaint();
                    }
                }
                else{
                    cota1 = AlturaB-e;
                    cota5 = AlturaC+e;
                    cota3 = (cota1+cota5)/2;
                    cota2 = (cota1+cota3)/2; 
                    cota4 = (cota3+cota5)/2; 

                    double[] arregloCota3 = {cota1, cota2, cota3, cota4, cota5};
                    arregloCota = arregloCota3;

                    error1 = MainProblema3Tanques.calcularError2(ArregloA, ArregloB, ArregloC, cota1);
                    error2 = MainProblema3Tanques.calcularError2(ArregloA, ArregloB, ArregloC, cota2);
                    error3 = MainProblema3Tanques.calcularError2(ArregloA, ArregloB, ArregloC, cota3);
                    error4 = MainProblema3Tanques.calcularError2(ArregloA, ArregloB, ArregloC, cota4);
                    error5 = MainProblema3Tanques.calcularError2(ArregloA, ArregloB, ArregloC, cota5);

                    double[] arregloDeError3 = {error1, error2, error3, error4, error5};
                    arregloDeError = arregloDeError3;

                    for (int i = 0; i < arregloDeError.length - 1; i++) {
                        errorActual = arregloDeError[i];
                        errorSiguiente = arregloDeError[i + 1];
                        if (errorActual < 0 && errorSiguiente > 0) {
                            System.out.println("El valor 0 está entre los errores " + errorActual + " y " + errorSiguiente);
                            cotaSuperior = arregloCota[i+1];
                            cotaInferior = arregloCota[i];
                            System.out.println("cota equivalentes "+cotaInferior+ " y "+ +cotaSuperior);
                            enMedio = true;
                            break;  // Terminamos el bucle una vez que encontramos el 0
                        }
                    }
                    double cota = MainProblema3Tanques.interpolacion(errorActual, cotaInferior, errorSiguiente, cotaSuperior);
                    double errorCota = MainProblema3Tanques.calcularError2(ArregloA, ArregloB, ArregloC, cota);
                    bandera = error>errorCota;
                    if (bandera == true) {
                        System.out.println("la cota es: "+ cota);
                        System.out.println("el error es: "+ errorCota);
                        respuestaCota=cota;
                        respuestaError=error;
                    }
                    while (bandera == false && numeroDeBucles < 100) {
                        if (errorCota > 0 && errorSiguiente > 0) {
                            cota2C = MainProblema3Tanques.interpolacion(errorCota, cota, errorActual, cotaInferior);
                        }
                        else{
                            cota2C = MainProblema3Tanques.interpolacion(errorCota, cota, errorSiguiente, cotaSuperior);
                        }
                        errorCota2C = MainProblema3Tanques.calcularError2(ArregloA, ArregloB, ArregloC, cota2C);
                        if (errorCota > 0 && errorSiguiente > 0) {
                            errorSiguiente = errorCota;
                            cotaSuperior = cota; 
                        }
                        else{
                            errorActual = errorCota;
                            cotaInferior = cota; 
                        }
                        cota =cota2C;
                        errorCota = errorCota2C;
                        if (error>errorCota2C) {
                            bandera = true;
                            respuestaCota=cota;
                            respuestaError=errorCota;
                        }
                        numeroDeBucles++;
                    }
                    System.out.println("el número de iteraciones es:"+numeroDeBucles);
                    if (numeroDeBucles > 99) {
                        JOptionPane.showMessageDialog(this, "los datos ingresados son incogruentes, por favor verifique", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        salidaCotaCalculada.setText(String.valueOf(respuestaCota));

                        Caso2 interfazCaso2 = new Caso2();
                        interfazCaso2.setSize(505, 320);
                        interfazCaso2.setLocation(0, 0);
                        interfazCaso2.jLAlturaA.setText(interfazCaso2.jLAlturaA.getText()+txtAlturaA.getText());
                        interfazCaso2.jLAlturaB.setText(interfazCaso2.jLAlturaB.getText()+txtAlturaB.getText());
                        interfazCaso2.jLAlturaC.setText(interfazCaso2.jLAlturaC.getText()+txtAlturaC.getText());

                        interfazCaso2.jLLongitudA.setText(interfazCaso2.jLLongitudA.getText()+txtLongitudA.getText());
                        interfazCaso2.jLLongitudB.setText(interfazCaso2.jLLongitudB.getText()+txtLongitudB.getText());
                        interfazCaso2.jLLongitudC.setText(interfazCaso2.jLLongitudC.getText()+txtLongitudC.getText());

                        interfazCaso2.jLDiametroA.setText(interfazCaso2.jLDiametroA.getText()+txtDiametroA.getText());
                        interfazCaso2.jLDiametroB.setText(interfazCaso2.jLDiametroB.getText()+txtDiametroB.getText());
                        interfazCaso2.jLDiametroC.setText(interfazCaso2.jLDiametroC.getText()+txtDiametroC.getText());

                        interfazCaso2.jLCoeficienteA.setText(interfazCaso2.jLCoeficienteA.getText()+txtCoeficienteCA.getText());
                        interfazCaso2.jLCoeficienteB.setText(interfazCaso2.jLCoeficienteB.getText()+txtCoeficienteCB.getText());
                        interfazCaso2.jLCoeficienteC.setText(interfazCaso2.jLCoeficienteC.getText()+txtCoeficienteCC.getText());

                        interfazCaso2.jLAlturaCalculada.setText(interfazCaso2.jLAlturaCalculada.getText()+String.valueOf(respuestaCota));

                        content.removeAll();
                        content.add(interfazCaso2.jPanel6, BorderLayout.CENTER);
                        content.revalidate();
                        content.repaint();
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Recuerde que la altura del tanque A tiene que ser mayor al tanque B y el tanque B mayor al tanque C", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } 
        else{
            //JOptionPane.showMessageDialog(this, "Complete todos los campos de los Tanques A, B y C", "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "Ingresa un número antes de continuar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
//        double  AlturaA = 100;
//        double  AlturaB = 90;
//        double  AlturaC = 80;
//        
//        double LongitudA = 4000;
//        double LongitudB = 6000;
//        double LongitudC = 5000;
//        
//        double DiametroA = 0.254;
//        double DiametroB = 0.2032;
//        double DiametroC = 0.1524;
//        
//        double CoeficienteCA = 150;
//        double CoeficienteCB = 150;
//        double CoeficienteCC = 150;
        
        //PARA NEGATIVOS
        
//        double  AlturaA = 250;
//        double  AlturaB = 240;
//        double  AlturaC = 60;
//        
//        double LongitudA = 4000;
//        double LongitudB = 6000;
//        double LongitudC = 5000;
//        
//        double DiametroA = 0.254;
//        double DiametroB = 0.2032;
//        double DiametroC = 0.1524;
//        
//        double CoeficienteCA = 150;
//        double CoeficienteCB = 150;
//        double CoeficienteCC = 150;
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtAlturaA.setText("");
        txtAlturaB.setText("");
        txtAlturaC.setText("");

        txtLongitudA.setText("");
        txtLongitudB.setText("");
        txtLongitudC.setText("");

        txtDiametroA.setText("");
        txtDiametroB.setText("");
        txtDiametroC.setText("");

        txtCoeficienteCA.setText("");
        txtCoeficienteCB.setText("");
        txtCoeficienteCC.setText("");
        
        salidaCotaCalculada.setText("");
        
        VistaInformacion informacion = new VistaInformacion();
        informacion.setSize(505, 320);
        informacion.setLocation(0, 0);
        content.removeAll();
        content.add(informacion.jPanel6, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAlturaAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaAKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtAlturaAKeyTyped

    private void txtLongitudAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudAKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtLongitudAKeyTyped

    private void txtDiametroAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametroAKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtDiametroAKeyTyped

    private void txtCoeficienteCAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoeficienteCAKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtCoeficienteCAKeyTyped

    private void txtAlturaBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaBKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtAlturaBKeyTyped

    private void txtLongitudBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudBKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtLongitudBKeyTyped

    private void txtDiametroBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametroBKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtDiametroBKeyTyped

    private void txtCoeficienteCBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoeficienteCBKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtCoeficienteCBKeyTyped

    private void txtAlturaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaCKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtAlturaCKeyTyped

    private void txtLongitudCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudCKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtLongitudCKeyTyped

    private void txtDiametroCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametroCKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtDiametroCKeyTyped

    private void txtCoeficienteCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoeficienteCCKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtCoeficienteCCKeyTyped

    private void txtErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErrorKeyTyped
        char c = evt.getKeyChar();
        if ((c< '0'|| c>'9') && (c != '.')) evt.consume();
    }//GEN-LAST:event_txtErrorKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JPanel content;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JTextField salidaCotaCalculada;
    public javax.swing.JTextField txtAlturaA;
    public javax.swing.JTextField txtAlturaB;
    public javax.swing.JTextField txtAlturaC;
    public javax.swing.JTextField txtCoeficienteCA;
    public javax.swing.JTextField txtCoeficienteCB;
    public javax.swing.JTextField txtCoeficienteCC;
    public javax.swing.JTextField txtCoeficienteCC1;
    public javax.swing.JTextField txtDiametroA;
    public javax.swing.JTextField txtDiametroB;
    public javax.swing.JTextField txtDiametroC;
    public javax.swing.JTextField txtDiametroC1;
    public javax.swing.JTextField txtError;
    public javax.swing.JTextField txtLongitudA;
    public javax.swing.JTextField txtLongitudB;
    public javax.swing.JTextField txtLongitudC;
    public javax.swing.JTextField txtLongitudC1;
    // End of variables declaration//GEN-END:variables
}
