/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author PROPIETARIO
 */
public class VistaInformacion extends javax.swing.JFrame {

    /**
     * Creates new form Caso1
     */
    public VistaInformacion() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLCoeficienteC = new javax.swing.JLabel();
        jLCoeficienteB = new javax.swing.JLabel();
        jLDiametroA = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCoeficienteC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLCoeficienteC.setText("Cota Menor");
        jPanel6.add(jLCoeficienteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 110, -1));

        jLCoeficienteB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLCoeficienteB.setText("Cota Media");
        jPanel6.add(jLCoeficienteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 130, -1));

        jLDiametroA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLDiametroA.setText("Cota Mayor");
        jPanel6.add(jLDiametroA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redimencion informacion.png"))); // NOI18N
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLCoeficienteB;
    public javax.swing.JLabel jLCoeficienteC;
    public javax.swing.JLabel jLDiametroA;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
